### PR TITLE
xyther14

### PR DESCRIPTION
**Pull request by xyther14**
Added the first Word Puzzle. It is a game of 5 word puzzles combined in a single word category.

- [x]  I have read the Code Of Conduct.
- [x]   I have followed all the steps of submission properly.

### CODE REVIEW

**Comment by xyther14** [comment]
The pubspec.yaml file didn't have the image_picker package so added it.

**Comment by harshptl14** [comment]
Hey @xyther14 after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
Other than that, all are good🙌

**Comment by xyther14** [comment]
> Hey @xyther14 after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
> Other than that, all are good🙌

Showing already up to day using 'git pull'

**Comment by harshptl14** [comment]
As you can see in [WordRiddleLists](https://github.com/clubgamma/RiddlesWorld/blob/master/lib/categories/words/WordriddleLists.dart) there is already one riddle which is order 1, so you need to change your riddle's order as the second. And if you can't see it in your repo, then make sure you pull it properly✋

**Comment by xyther14** [comment]
Added a new PR with latest pull changes so closing this.

**Pull request closed without merging**
