### PR TITLE
bibekpanda55

### PR DESCRIPTION
**Pull request by bibekpanda55**
Added audios folder within assets folder which include 4 animation sounds which get played onClick of every item in list of all puzzles and also on result page of the puzzle.

### CODE REVIEW

**Comment by harshptl14** [comment]
Hey @bibekpanda55, Audio is working fine🤟, but can you change the onTap sound effect? For reference, you can Install the Clash-Royal game for a better understanding. I am not saying that I need that sound but similar to that sound! And add onTap sound in the Category section also😶. Other than that all are good🚀✨

**Comment by bibekpanda55** [comment]
Sure @harshptl14  I will do that but can you merge this PR and I will create another PR as per your requirement

**Comment by harshptl14** [comment]
@bibekpanda55, It would be great if you make all changes and then we merge it.👀

**Comment by bibekpanda55** [comment]
Ok will do that changes and make another PR today itself , do you need different onTap sound on categories and puzzle list or same sound will do?

**Comment by harshptl14** [comment]
Same for Catagory and Puzzle🙌, do check the OnTap sound of Clash-Royal Game (not Compulsory)✋

**Comment by bibekpanda55** [comment]
Yeah done

**Comment by bibekpanda55** [comment]
Hey @harshptl14 I have done the changes  as per your requirement, I found same sound little bit of irritating and monotonous so added different sound please review  and merge it🙂

**Comment by harshptl14** [comment]
@bibekpanda55, so this is perfect but can you add a toggle to switch mute/music mode?👀

**Comment by bibekpanda55** [comment]
Yeah @harshptl14  I can do that  , I will make one new PR for that please merge this PR for now.

**Comment by harshptl14** [comment]
You can give a PR in the SoundEffects branch. After all changes in the SoundEffects branch, I will merge it in master!

**Comment by bibekpanda55** [comment]
But @harshptl14 where do you want me to place the toggle button like there's no settings page as such?

**Comment by harshptl14** [comment]
[In settings Page](https://github.com/clubgamma/RiddlesWorld/blob/SoundEffects/lib/categories/Preference/Preference.dart)🙌

**Comment by bibekpanda55** [comment]
Hey @harshptl14   for settings you have already merged some changes so I have do delete my old cloned repo and work from beggining of sound issue that would be frustrating so can you merge this PR then I can work on the repo for toggle button

**Comment by harshptl14** [comment]
As you can see, there are lots of conflicts, so you need to pull all those changes, then and only then I can merge your PR😬😶

**Comment by bibekpanda55** [comment]
So @harshptl14 I will once again make a PR after adding sound effects please accept the PR and you can create a new issue regarding the toggle button will that be fine?

**Pull request closed without merging**
