### PR TITLE
mayankparida

### PR DESCRIPTION
**Pull request by mayankparida**
I have updated riddle 11 for the math section. Please do check n merge. Thank you!

### CODE REVIEW

**Comment by harshptl14** [comment]
Hey @mayankparida, this riddle is already added [see here](https://github.com/clubgamma/RiddlesWorld/pull/21/files).

Can you make another distinction?

**Comment by mayankparida** [comment]
Ok sure I'll add a different riddle. Sorry for the inconvenience.

**Comment by mayankparida** [comment]
Please could you check now? I have changed to riddle to an amazing card deck riddle. Please do check and marge.

**Comment by harshptl14** [comment]
can you go through [CONTRIBUTING.md](https://github.com/clubgamma/RiddlesWorld/blob/master/CONTRIBUTING.md), and make changes accordingly🙌. Other than that, the riddle is awesome!

**Comment by mayankparida** [comment]
I'm actually very new to this. I just now did exactly what you said to do on the contributing file. What do I do after git pull upstream master?

**Comment by harshptl14** [comment]
Do this🙌

**Review by mayankparida — COMMENTED** [review]
- [X] I have read the Code Of Conduct.
        
    - [X] I have followed all the steps of submission properly.

**Comment by mayankparida** [comment]
I'm really sorry but I'm not able to do it properly.

**Review by harshptl14 — APPROVED** [review]
Thanks,@mayankparida, for opening the pull request! 👏

I have reviewed your pull request thoroughly, and it's perfect!

Star ⭐ this project would be great! You can also [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions🤟
Join the [discord channel of club gamma🙌](https://discord.gg/kjnp6wU)

**Comment by harshptl14** [comment]
> I'm really sorry but I'm not able to do it properly.

It's Okay!

**Comment by mayankparida** [comment]
Thank you very very much. Honestly, this project is really good. All the best!

**Pull request merged**
