### PR TITLE
Added Math Riddle

### PR DESCRIPTION
**Pull request by sdmmssa**

### CODE REVIEW

**Comment by harshptl14** [comment]
Hey @sdmmssa after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
Other than that, all are good🙌

**Comment by harshptl14** [comment]
And don't forget to add this two-line in the comment section when you give us PR🙌
- [X] I have read the Code Of Conduct.
- [X] I have followed all the steps of submission properly.

**Comment by sdmmssa** [comment]
created a new updated pull request

**Comment by harshptl14** [comment]
Your other PR is merged so closing this

**Pull request closed without merging**
