### PR TITLE
updated pull request.

### PR DESCRIPTION
**Pull request by Denish-Ranpariya**
I have read the Code Of Conduct.
I have followed all the steps of submission properly.
I have added one math riddle.

### CODE REVIEW

**Comment by harshptl14** [comment]
Hey @Denish-Ranpariya, It's an empty file!😶🤔

**Comment by Denish-Ranpariya** [comment]
Sorry @harshptl14 , It was done by a mistake. I have done a commit after adding that file.

**Review by harshptl14 — APPROVED** [review]
Thanks,@Denish-Ranpariya, for opening the pull request! 👏

I have reviewed your pull request thoroughly, and it's perfect!

Star ⭐ this project would be great! You can also [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions🤟
Join the [discord channel of club gamma🙌](https://discord.gg/kjnp6wU)

**Comment by Denish-Ranpariya** [comment]
Sure @harshptl14. Thanks for merging the PR.

**Comment by harshptl14** [comment]
@Denish-Ranpariya, It's my pleasure! Thanks for contributing🙌

**Pull request merged**
