### PR TITLE
ADDED A MATH RIDDLE

### PR DESCRIPTION
**Pull request by madhavtripathi05**
FIXED A TYPO
**If the project breaks due to incompatibility of Dart SDK, revert pubspec.lock with the older one.**

### CODE REVIEW

**Comment by madhavtripathi05** [comment]
- [X] I have read the Code Of Conduct.
- [X] I have followed all the steps of submission properly.

**Comment by harshptl14** [comment]
Hey @madhavtripathi05 after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
Other than that, all are good🙌

**Comment by madhavtripathi05** [comment]
Done

**Review by harshptl14 — APPROVED** [review]
Thanks,@madhavtripathi05, for opening the pull request! 👏

I have reviewed your pull request thoroughly, and it's perfect!

Star ⭐ this project and [tweet](https://twitter.com/share?text=Contributed+to+awesome+projects+at+@club_gamma&url=https://clubgamma.github.io/hacktoberfest) about your contributions and also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)

**Pull request merged**
