### PR TITLE
Github username bibekpanda55

### PR DESCRIPTION
**Pull request by bibekpanda55**
Added a math riddle with title magic number and completed its requisites.

### CODE REVIEW

**Comment by harshptl14** [comment]
Hey @bibekpanda55 after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
Other than that, all are good🙌

And also go through the [CONTRIBUTING.md](https://github.com/clubgamma/RiddlesWorld/blob/master/CONTRIBUTING.md) and make some changes accordingly.

**Comment by bibekpanda55** [comment]
> Hey @bibekpanda55 after you, there were 2-3 PR has been merged, so can you pull all these changes and send us PR once again!!
> Other than that, all are good🙌
> 
> And also go through the [CONTRIBUTING.md](https://github.com/clubgamma/RiddlesWorld/blob/master/CONTRIBUTING.md) and make some changes accordingly.

Ok will do that in a minute

**Comment by harshptl14** [comment]
Hey @bibekpanda55, @razorcalhn is also chaning [this issue](https://github.com/clubgamma/RiddlesWorld/pull/29), so wait some time and  let him give the PR and after him make changes into that. 

Sorry for inconvenience😶

**Comment by razorcalhn** [comment]
Hello, I've pulled all the changes into my forked repo and changed my files
accordingly.
Sent another PR, lemme know if there's an issue.
:)

**Pull request closed without merging**
