### PR TITLE
Denish-Ranpariya

### PR DESCRIPTION
**Pull request by Denish-Ranpariya**
I have read the Code Of Conduct.
I have followed all the steps of submission properly.
I have added new riddle in findTheThing section.

### CODE REVIEW

**Review by harshptl14 — APPROVED** [review]
Thank you @Denish-Ranpariya for giving us the PR.🙌

**Comment by yashpaneliya** [comment]
Hello contributor👋,

As we all know that Hacktoberfest-2020 is ended. Hope you enjoyed it a lot and made some awesome contributions. 
So now it's time for schwags🎁🤩

**Send your email (linked with your GitHub account) in the reply of this comment. Mention any one of the maintainers (@yashpaneliya @rudrabarad @harshptl14 @chirayu-joshi @dhruvpatel1706 ) in the reply.**

**We'll send a form on the email you'll provide. Please reply ASAP.**

Join [Club Gamma Discord](https://discord.com/invite/kjnp6wU) for future updates.

**Comment by Denish-Ranpariya** [comment]
Thank you @yashpaneliya 
It was a wonderful experience.
I learned many features of git and github during the fest.
My email id: ranpariyadenish1512@gmail.com

**Comment by yashpaneliya** [comment]
Great @Denish-Ranpariya 👏👏. Keep going 🙌.

You'll receive an email today for the swags form.

**Comment by Denish-Ranpariya** [comment]
> Great @Denish-Ranpariya 👏👏. Keep going 🙌.
> 
> You'll receive an email today for the swags form.

Haven't received the email.

**Pull request merged**
